data_file:
  # when local_directory is set the data files will processed from this local directory and AWS properties will be ignored
  #local_directory: 'C:\PRJ\OWH\ICD10'
  # AWS S3 bucket information, when local_directory peroperty is not specified above, the ETL will try to download the data files
  # from the directory in the AWS S3 bucket specified below
  aws_access_key_id: 'AKIAIUL32Z4YYJG234NQ'
  aws_secret_access_key: '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'
  aws_s3_bucket_name: 'owh-data'
  aws_s3_directory: 'datasets/icd10'
# No data is loaded into Elastic search, but since the ETL uses the common ETL framework, the configuration is neede and it creates an empty index
elastic_search:
  host: 127.0.0.1
  port: 9200
  bulk_load_size: 10000
  index: icd
  type: icd
  type_mapping: icd10-mapping.json