# Default config
default: 
  elastic_search:
    url: 'http://localhost:9200/'
  yrbs:
    queryUrl: ''
    questionsUrl: ''
  wonder:
    url: 'http://54.242.94.197/wonder/'
    apix_project: ''
    apix_token: ''
  logging:
    level: 'debug'
  fb:
    appID :
    appURL:
  disableQueryCache: false
