# Default config
default: 
  elastic_search:
    url: 'https://search-owh-prod-j72vdl44huddysgj5y25v4z6su.us-east-1.es.amazonaws.com'
  yrbs:
    queryUrl: 'http://34.232.240.197:7777/stats' 
    questionsUrl: 'http://34.232.240.197:7777/questions'
  wonder:
    url: 'https://search-owh-prod-j72vdl44huddysgj5y25v4z6su.us-east-1.es.amazonaws.com/wonder/'
    apix_project: ''
    apix_token: ''
  logging:
    level: 'debug'
  fb:
    appID :
    appURL:
  disableQueryCache: false
