-# Default config		
 -default: 		
 -  elastic_search:		
 -    url: 'http://localhost:9200/'		
 -  yrbs:		
 -    queryUrl: ''		
 -    questionsUrl: ''		
 -  wonder:		
 -    url: 'http://34.206.155.198/wonder/'
 -    apix_project: ''		
 -    apix_token: ''		
 -  logging:		
 -    level: 'debug'		
 -  fb:		
 -    appID :		
 -    appURL:
 -  googleAnalytics:
      trackingID: ''
 -  disableQueryCache: false
