data_file:
  # when local_directory is set the data files will processed from this local directory and AWS properties will be ignored
  local_directory: 'C:\PRJ\OWH\WORK\owh-ds\software\owh\backoffice\WORK\20170522.180503'
  # AWS S3 bucket information, when local_directory peroperty is not specified above, the ETL will try to download the data files
  # from the directory in the AWS S3 bucket specified below
  #aws_access_key_id: 'AKIAIS6PE7BUEWSY2FQA'
  #aws_secret_access_key: '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'
  aws_s3_bucket_name: 'owh-data'
  aws_s3_directory: 'datasets/census'
elastic_search:
  host: 127.0.0.1
  port: 9200
  bulk_load_size: 10000
  index: owh_census
  type: census
  type_mapping: census-type-mapping.json
